###
GET http://localhost:8081/server/api/v1/?id=1
Accept: application/json

###
GET http://localhost:8080/client/api/v1/run
Accept: application/json

###

GET http://localhost:8080/client/api/v1/stop
Accept: application/json

###
PUT http://localhost:8081/server/api/v1
Content-Type: application/json

{
  "id": "3",
  "changeFunds": "1"
}

###

GET http://localhost:8081/server/api/v1?id=5
Accept: application/json

###

GET http://localhost:8081/actuator/metrics/http.server.requests
Accept: application/json

###

GET http://localhost:8081/actuator/prometheus
Accept: text/plain