achilles:
  client:
    serverUrl: "http://localhost:8081/server/api/v1"
    threadCount: 1000
    readQuota: 5
    writeQuota: 5
    readIdList: 1,2,3,4,5,6,7,8,9,10
    writeIdList: 1,2,3,4,5,6,7,8,9,10
    isLooped: false